name: Publish package to PyPi

on:
  push:
    branches:
      - 'main'


jobs:
  publish_pypi:
    name: build upload pacakge to PyPi
    runs-on: ubuntu-latest

    steps:
      - name: check main branch
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Check package installation
        run: pip install -e .

      - name: Build package
        run: |
          python3 -m pip install --upgrade build
          python3 -m build --sdist

      - name: upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pip install twine
          twine upload --skip-existing dist/*.tar.gz
